#!/bin/bash

TS_START=$(date +%s)

echo Applying configuration
ansible-playbook -i inventory.yaml -c local playbook.yml
RES=$?

echo Took $(($(date +%s) - $TS_START)) seconds

if [ "$RES" == "0" ]; then
	git rev-parse HEAD > .latest-success
fi
