#!/bin/bash

TS_START=$(date +%s)

TAGS=""
ARGS=()

for arg in "$@"; do
    case $arg in
        --user|-u)
            TAGS="--tags user"
            ;;
        --system|-s)
            TAGS="--tags system"
            ;;
        *)
            ARGS+=("$arg")
            ;;
    esac
done

if [ "$TAGS" == "--tags user" ]; then
    echo "Applying user environment configuration (no sudo)..."
else
    echo "Getting sudo access..."
    sudo echo "Applying configuration..."
fi

ansible-playbook -i inventory.yaml -c local playbook.yml $TAGS "${ARGS[@]}"
RES=$?

echo Took $(($(date +%s) - $TS_START)) seconds

if [ "$RES" == "0" ]; then
	git rev-parse HEAD > .latest-success
fi
