#!/bin/bash

ME=$(hostname)
TS=$(date +%Y%m%d)

TMPDIR="/tmp/"
BACKUPDIR="/tmp/"
SYSCONFDIR=$(dirname $0)


BACKUP=${BACKUPDIR}/backup-${ME}.${TS}.backup.tgz.gpg

if [ "${SYSCONFDIR}" == "." ];
then
	echo "Must be called with absolute path."
	exit 1
fi

for role in roles/*;
do
	echo "Checking $role"
	cd $role
	if [ -n "$(git status --porcelain)" ];
	then
		echo "  $role is not clean"
		git status --porcelain
		exit 1
	else
		echo "  ok"
	fi
	cd - > /dev/null
done

sudo tar czf - ${SYSCONFDIR} /etc/ | gpg -r 1104326B03598030D64CC39EEA076B1ED3FDDBC0 --encrypt > ${BACKUP}

if [ ! -s "${BACKUP}" ];
then
	echo Poblem with backup
fi
