- src: https://github.com/seb4stien/ansible.cli
- src: https://github.com/seb4stien/ansible.python
- src: https://github.com/seb4stien/ansible.user
- src: https://github.com/seb4stien/ansible.ssh-tunnel-endpoint
