- name: Install graphic apps I use a lot
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dconf-editor
    - gedit
    - gnome-shell-extensions
    - gnome-tweaks
    - terminator
    - wmctrl

- name: Remove terminator title bar
  ansible.builtin.copy:
    src: files/home/config/terminator/config
    dest: "{{ user_home }}/.config/terminator/config"
