- name: Configure natural scrolling for touchpad
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present

- name: Configure terminal shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/terminal"
    value: "['<Super>t']"
    state: present
