- name: Install basic tools
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autojump
    - curl
    - git
    - mailutils
    - screen
    - tree
    - vim
    - wget

- name: Default editor
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Configuring bash preferences
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      alias ga='git add'
      alias gs='git status'
      alias gc='git commit'
      alias gd='git diff'
      alias gr='git fetch --all && git rebase'
      alias gP='git push'
      . /usr/share/autojump/autojump.sh

- name: Configuring ls aliases
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: "{{ item }}"
  loop:
    - alias ll='ls -alF'
    - alias la='ls -A'
    - alias l='ls -CF'
