- name: Install graphic apps I use a lot
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - terminator
    - gedit
    - dconf-editor

- name: Remove terminator title bar
  ansible.builtin.copy:
    src: files/config/terminator/config
    dest: "{{ user_home }}/.config/terminator/config"
