- name: Install packages for python
  become: true
  apt:
    state: present
    name:
    - python3
    - python3-pip
    - python3-poetry
    - pipenv

- name: Store pipenv venv per project
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: PIPENV_VENV_IN_PROJECT=1

- name: Remove previous virtualenvs
  ansible.builtin.file:
    path: "{{ user_home }}/.local/share/virtualenvs"
    state: absent
