- name: Create my standard directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
  - "{{ user_home }}/bin"
  - "{{ user_home }}/perso/src"
  - "{{ user_home }}/share"
  - "{{ user_home }}/src"
  - "{{ user_home }}/tmp"

- name: Create symlinks to personal tooling
  ansible.builtin.file:
    path: "{{ user_home }}/bin/{{ item }}"
    src: "{{ user_home }}/system-config/files/home/bin/{{ item }}"
    state: link
    mode: '0700'
  loop:
    - backup-conf
    - how
    - system-config-apply

- name: Remove previous versions
  ansible.builtin.file:
    path: "{{ user_home }}/bin/sc"
    state: absent
