- name: Create my standard directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
  - "{{ user_home }}/bin"
  - "{{ user_home }}/perso/src"
  - "{{ user_home }}/src"
  - "{{ user_home }}/tmp"

- name: Create useful symlinks
  ansible.builtin.file:
    path: "{{ user_home }}/bin/sc"
    src: "{{ user_home }}/system-config/files/home/bin/sc"
    state: link
    mode: '0700'
