- name: Install packages for personal usage
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libfuse2 # for Ledger live

- name: Set git config
  git_config:
    name: user.name
    scope: global
    value: "{{ user_name }}"

- name: Set git config
  git_config:
    name: user.email
    scope: global
    value: "{{ user_mail }}"
