- name: Install SSH server
  become: true
  apt:
    state: present
    name:
    - openssh-server

- name: Disable root login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin" 
    line: "PermitRootLogin no" 
    state: present
  notify: restart ssh

- name: Disable password login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication no" 
    state: present
  notify: restart ssh

- name: Limit login to user
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowUsers" 
    line: "AllowUsers {{ user }}"
    state: present
  notify: restart ssh
