- name: Install CLIs
  become: true
  apt:
    state: present
    name:
    - apt-file
    - autojump
    - curl
    - iftop
    - jshon
    - git
    - gawk  # for git-summary
    - gddrescue # rescude disks & cards
    - lvm2
    - mailutils
    - screen
    - rmlint
    - testdisk  # rescude disks & cards
    - tree
    - unattended-upgrades
    - vim
    - wget

- name: Default editor
  become: true
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Default editor
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Configuring bash preferences
  ansible.builtin.blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      alias ga='git add'
      alias gs='git status'
      alias gc='git commit'
      alias gd='git diff'
      alias gr='git fetch --all && git rebase'
      alias gP='git push'
      alias GS='git-summary ~/system-config; git-summary ~/perso/src/; git-summary ~/src/'
      alias SC='~/bin/system-config-apply'
      . /usr/share/autojump/autojump.sh
      export PATH=$PATH:$HOME/system-config/files/home/bin/

- name: Configuring ls aliases
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: "{{ item }}"
  loop:
    - alias ll='ls -alF'
    - alias la='ls -A'
    - alias l='ls -CF'

- name: Set git username
  git_config:
    name: user.name
    scope: global
    value: "{{ user_name }}"

- name: Set git email
  git_config:
    name: user.email
    scope: global
    value: "{{ user_mail }}"

- name: Set git pull strategy
  git_config:
    name: pull.rebase
    scope: global
    value: true

- name: Set default master branch name
  git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Install git summary
  ansible.builtin.git:
    repo: https://github.com/MirkoLedda/git-summary.git
    dest: "{{ user_home }}/share/git-summary"
    clone: yes
    update: yes

- name: Link git summary
  ansible.builtin.file:
    path: "{{ user_home }}/bin/git-summary"
    src: "{{ user_home }}/share/git-summary/git-summary"
    state: link
    mode: '0700'
