- name: Install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/Vundle.vim"

- name: Personnal vim configuration
  file:
    state: link
    src: "{{ role_path }}/files/home/vimrc"
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
