- name: Add Apt signing key
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Install Google chrome apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install GUIs
  apt:
    state: present
    name:
    - autokey-gtk
    - dconf-editor
    - deja-dup
    - gedit
    - gimp
    - google-chrome-stable
    - gnome-shell-extensions
    - gnome-tweaks
    - remmina
    - terminator
    - v4l-utils  # to configure my webcam
    - wmctrl
    - xclip
