- name: Create terminator config folder
  ansible.builtin.file:
    path: "{{ user_home }}/.config/terminator/"
    state: directory

- name: Remove terminator title bar
  ansible.builtin.copy:
    src: files/home/config/terminator/config
    dest: "{{ user_home }}/.config/terminator/config"
